replicaCount: 1
subset: v1
image:
  repository: docker.io/fintechinnovation
  name: sre-coding-challenge-service-a
  tag: latest
  pullPolicy: Always

label:
  app: service-a

securityContext:
  runAsUser: 1000
  fsGroup: 1000

readinessProbe:
  enabled: true
  httpPath: "/healthz"

resources:
  requests:
    cpu: "0.03"
    memory: "256Mi"
  limits:
    memory: "512Mi"

service:
  enabled: true
  port: 5000
  portName: http


networkPolicy:
  enabled: true
  applyToLabels:
    app: service-a
  egress:
    - protocol: TCP
      port: 8888
      selectors:
        - app: service-b
