replicaCount: 1
subset: v1
image:
  name: service-b
  tag: test
  pullPolicy: IfNotPresent

label:
  app: service-b

securityContext:
  runAsUser: 1000
  fsGroup: 1000

readinessProbe:
  enabled: true
  httpPath: "/healthz"

resources:
  requests:
    memory: "300Mi"
  limits:
    cpu: "0.5"
    memory: "200Mi"

service:
  enabled: true
  port: 8888
  portName: http


networkPolicy:
  enabled: true
  applyToLabels:
    app: service-b
  ingress:
    - protocol: TCP
      port: 8888
      selectors:
        - app: service-a
